version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydraflow-web
    restart: always
    volumes:
      - .:/app   # Maps the current directory to /app in the container
    ports:
      - "5000:5000"   
    environment:
      FLASK_ENV: production
      SECRET_KEY: your_secret_key
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/daily_reports_db
    depends_on:
      - postgres  
  postgres:
    image: postgres:latest
    container_name: hydraflow-postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data  # Persists database data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: daily_reports_db
    ports:
      - "5432:5432"  

volumes:
  postgres:   
