

name: Docker Build and Push to Insecure Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Insecure Registry
        run: |
          echo "{ \"insecure-registries\": [\"116.58.60.115:6000\"] }" | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Build Docker Image
        run: |
          docker build -t hydraflow:latest .

      - name: Tag Docker Image
        run: |
          docker tag hydraflow:latest 116.58.60.115:6000/hydraflow:latest

      - name: Push Docker Image to Insecure Registry
        run: |
          docker push 116.58.60.115:6000/hydraflow:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 116.58.60.115:6000/hydraflow:latest

      - name: SSH to remote server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 116.58.60.115
          username: shirjeel-afzal
          password: shirjeel
          script: |
            cd ~/TheHexaa/HydraFlow
            docker-compose down
            docker-compose up -d